/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["getAllUsers"];
        put?: never;
        /** Create a new user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: operations["getUserById"];
        put?: never;
        post?: never;
        /** Delete user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all calculators */
        get: operations["getAllCalculators"];
        put?: never;
        /** Create a new calculator */
        post: operations["createCalculator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculators/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get calculator by ID */
        get: operations["getCalculatorById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculators/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get calculator versions */
        get: operations["getCalculatorVersions"];
        put?: never;
        /** Add a new version */
        post: operations["addCalculatorVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user calculations */
        get: operations["getCalculations"];
        put?: never;
        /** Create a new calculation */
        post: operations["createCalculation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculations/{id}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get scenarios for calculation */
        get: operations["getScenarios"];
        put?: never;
        /** Add a scenario */
        post: operations["addScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculations/{id}/select-scenario/{scenarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Select active scenario */
        put: operations["selectScenario"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @enum {string} */
        ProductType: "LOAN" | "DEPOSIT";
        /** @enum {string} */
        InterestMethod: "SIMPLE" | "COMPOUND";
        /** @enum {string} */
        DayCountConvention: "ACTUAL_365" | "ACTUAL_360" | "THIRTY_360" | "ACTUAL_ACTUAL";
        /** @enum {string} */
        RateType: "FIXED" | "FLOATING";
        /** @enum {string} */
        Frequency: "ONCE" | "DAILY" | "WEEKLY" | "BI_WEEKLY" | "MONTHLY" | "QUARTERLY" | "SEMI_ANNUALLY" | "ANNUALLY";
        /** @enum {string} */
        AmortizationType: "ANNUITY" | "LINEAR" | "BULLET" | "ZERO_COUPON";
        /** @enum {string} */
        CurrencyCode: "USD" | "EUR" | "UAH" | "GBP";
        /** @enum {string} */
        RoundingMode: "UP" | "DOWN" | "CEILING" | "FLOOR" | "HALF_UP" | "HALF_DOWN" | "HALF_EVEN" | "UNNECESSARY";
        UserDto: {
            /** Format: uuid */
            id?: string;
            username?: string;
            /** Format: email */
            email?: string;
            firstName?: string;
            lastName?: string;
            profilePictureUrl?: string;
            role?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateUserRequest: {
            username: string;
            password: string;
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            profilePictureUrl?: string;
            role?: string;
        };
        PageUserDto: {
            content?: components["schemas"]["UserDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
        CalculatorDto: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            description?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateCalculatorRequest: {
            code: string;
            name: string;
            description?: string;
            algorithmMetadata: components["schemas"]["FinancialProductDefinitionDto"];
        };
        CalculatorVersionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            calculatorId?: string;
            version?: number;
            algorithmMetadata?: components["schemas"]["FinancialProductDefinitionDto"];
            /** Format: date-time */
            createdAt?: string;
        };
        CreateVersionRequest: {
            algorithmMetadata: components["schemas"]["FinancialProductDefinitionDto"];
        };
        FinancialProductDefinitionDto: {
            type: components["schemas"]["ProductType"];
            interest: components["schemas"]["InterestConfigDto"];
            repayment: components["schemas"]["RepaymentConfigDto"];
            constraints?: components["schemas"]["ProductConstraintsDto"];
            defaults?: components["schemas"]["ProductDefaultsDto"];
        };
        InterestConfigDto: {
            method: components["schemas"]["InterestMethod"];
            dayCountConvention: components["schemas"]["DayCountConvention"];
            rateType: components["schemas"]["RateType"];
            accrualFrequency?: components["schemas"]["Frequency"];
            compoundingFrequency?: components["schemas"]["Frequency"];
        };
        RepaymentConfigDto: {
            strategy: components["schemas"]["AmortizationType"];
            frequency: components["schemas"]["Frequency"];
        };
        ProductConstraintsDto: {
            minAmount?: number;
            maxAmount?: number;
            minTerm?: number;
            maxTerm?: number;
            minRate?: number;
            maxRate?: number;
        };
        ProductDefaultsDto: {
            fixedRate?: number;
            /** @default USD */
            currency: components["schemas"]["CurrencyCode"];
            /** @default 2 */
            roundingScale: number;
            /** @default HALF_UP */
            roundingMode: components["schemas"]["RoundingMode"];
        };
        CalculationInputDto: {
            amount: number;
            rate?: number;
            term?: number;
            /** Format: date */
            startDate?: string;
        };
        PageCalculatorDto: {
            content?: components["schemas"]["CalculatorDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
        CalculationDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            calculatorId?: string;
            /** Format: uuid */
            calculatorVersionId?: string;
            currency?: string;
            /** Format: uuid */
            selectedScenarioId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateCalculationRequest: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            calculatorId: string;
            inputData: components["schemas"]["CalculationInputDto"];
            currency?: string;
        };
        CalculationScenarioDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            calculationId?: string;
            scenarioName?: string;
            scenarioInput?: components["schemas"]["CalculationInputDto"];
            scenarioResult?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt?: string;
        };
        CreateScenarioRequest: {
            scenarioName?: string;
            scenarioInput: components["schemas"]["CalculationInputDto"];
        };
        PageCalculationDto: {
            content?: components["schemas"]["CalculationDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            size?: number;
            number?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful. Returns user info in body and tokens in HttpOnly cookies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed successfully. Returns new user info and sets new access token cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful. Clears cookies. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description Username or email already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllUsers: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageUserDto"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
        };
    };
    getUserById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllCalculators: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of calculators */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCalculatorDto"];
                };
            };
        };
    };
    createCalculator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCalculatorRequest"];
            };
        };
        responses: {
            /** @description Calculator created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorDto"];
                };
            };
        };
    };
    getCalculatorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calculator found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorDto"];
                };
            };
        };
    };
    getCalculatorVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorVersionDto"][];
                };
            };
        };
    };
    addCalculatorVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionRequest"];
            };
        };
        responses: {
            /** @description Version added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorVersionDto"];
                };
            };
        };
    };
    getCalculations: {
        parameters: {
            query: {
                userId: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of calculations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCalculationDto"];
                };
            };
        };
    };
    createCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCalculationRequest"];
            };
        };
        responses: {
            /** @description Calculation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationDto"];
                };
            };
        };
    };
    getScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scenarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationScenarioDto"][];
                };
            };
        };
    };
    addScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScenarioRequest"];
            };
        };
        responses: {
            /** @description Scenario added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculationScenarioDto"];
                };
            };
        };
    };
    selectScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                scenarioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario selected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
